language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.6
  - 7.1

before_script:
  - composer install --prefer-dist
  - cd tests/

script: ../vendor/bin/phpunit
