language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.6
  - 7.0

before_script:
  - composer install --prefer-dist

script: ./vendor/bin/phpunit -c tests/phpunit.xml
